parameters:
    api_errors:
        400: []     #HTTP_BAD_REQUEST
        401: []     #HTTP _UNAUTHORIZED
        402: []     #HTTP _PAYMENT_REQUIRED
        403: []     #HTTP _FORBIDDEN
        404: []     #HTTP _NOT_FOUND
        405: []     #HTTP _METHOD_NOT_ALLOWED
        406: []     #HTTP _NOT_ACCEPTABLE
        407: []     #HTTP _PROXY_AUTHENTICATION_REQUIRED
        408: []     #HTTP _REQUEST_TIMEOUT
        409: []     #HTTP _CONFLICT
        410: []     #HTTP _GONE
        411: []     #HTTP _LENGTH_REQUIRED
        412: []     #HTTP _PRECONDITION_FAILED
        413: []     #HTTP _REQUEST_ENTITY_TOO_LARGE
        414: []     #HTTP _REQUEST_URI_TOO_LONG
        415: []     #HTTP _UNSUPPORTED_MEDIA_TYPE
        416: []     #HTTP _REQUESTED_RANGE_NOT_SATISFIABLE
        417: []     #HTTP _EXPECTATION_FAILED
        418: []     #HTTP _I_AM_A_TEAPOT
        421: []     #HTTP _MISDIRECTED_REQUEST
        422: []     #HTTP _UNPROCESSABLE_ENTITY
        423: []     #HTTP _LOCKED
        424: []     #HTTP _FAILED_DEPENDENCY
        425: []     #HTTP _RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL
        426: []     #HTTP _UPGRADE_REQUIRED
        428: []     #HTTP _PRECONDITION_REQUIRED
        429: []     #HTTP _TOO_MANY_REQUESTS
        431: []     #HTTP _REQUEST_HEADER_FIELDS_TOO_LARGE
        451: []     #HTTP _UNAVAILABLE_FOR_LEGAL_REASONS
        500: []     #HTTP _INTERNAL_SERVER_ERROR
