api_login_check:
    path: /api/login_check

api:
    resource: '.'
    type: 'api_platform'
    prefix: /api

sibers_api:
    resource: "@SibersApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"