api_login_check:
    path: /api/login_check

app_main:
    resource: '@AppBundle/Controller/'
    type: 'annotation'
    prefix:   /api/main

api:
    resource: '.'
    type: 'api_platform'
    prefix: /api

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sibers_api:
    resource: "@SibersApiBundle/Controller/"
    type:     annotation
    prefix:   /



app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

