imports:
#    - { resource: '@Sibers/ApiBundle/Resources/config/event_listeners.yml' }

services:
#    sibers_api.example:
#        class: Sibers\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
